export default {
  light: {
    cover: { Story: '#8D6E63', Poem: '#6D4C41' },
    coverBorder: '#4E342E',
    separator: '#ACACAC',
    icon: '#000000',
    disabledIcon: '#AAAAAA',
    text: '#000000',
    title: 'white',
    primary: '#D7CCC8',
    secondary: '#979797',
    switch: '#6D4C41',
    slider: '#D7CCC8',
    sliderHandler: '#6D4C41',
    sliderBuffer: '#C3A89E',
    contentColor: 'black'
  },
  dark: {
    cover: { Story: '#EEEEEE', Poem: '#BFBFBF' },
    coverBorder: '#4E342E',
    separator: '#ACACAC',
    icon: '#EEEEEE',
    disabledIcon: '#AAAAAA',
    text: '#EEEEEE',
    title: 'black',
    primary: '#53535B',
    secondary: '#979797',
    switch: '#BFBFBF',
    slider: '#EEEEEE',
    sliderHandler: '#949494',
    sliderBuffer: '#CFCFCF',
    contentColor: 'white'
  },
  clean: {
    cover: { Story: '#DF5A48', Poem: '#E27A3F' },
    coverBorder: '#4E342E',
    separator: '#ACACAC',
    icon: '#000000',
    disabledIcon: '#AAAAAA',
    text: '#000000',
    title: 'white',
    primary: '#D4D4D4',
    secondary: '#979797',
    switch: '#DF5A48',
    slider: '#D7CCC8',
    sliderHandler: '#6D4C41',
    sliderBuffer: '#C3A89E',
    contentColor: 'black'
  },
  indigo: {
    cover: { Story: '#00A8E8', Poem: '#0567BC' },
    coverBorder: '#4E342E',
    separator: '#ACACAC',
    icon: '#FFFFFF',
    disabledIcon: '#AAAAAA',
    text: '#FFFFFF',
    title: 'white',
    primary: '#00171F',
    secondary: '#979797',
    switch: '#0567BC',
    slider: '#EEEEEE',
    sliderHandler: '#BFBFBF',
    sliderBuffer: '#CFCFCF',
    contentColor: 'white'
  }
};
