# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeaTimes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TeaTimes
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

#  target 'TeaTimes-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'TeaTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TeaTimes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeaTimes-tvOS

  target 'TeaTimes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
